[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }

[dev]
  command = "npm run start"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"

# Using the `.toml` version of this config file as plugins don't seem to work with the .yml style.
[[plugins]]
  package = "/plugins/sass"
